In [1]:
!pip install pandas

In [2]:
!pip install tensorflow-macos==2.16.1

In [4]:
!pip install keras

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
## One Hot Representation For Every Word
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1427, 5280, 7416, 4025],
 [1427, 5280, 7416, 5361],
 [1427, 1563, 7416, 1409],
 [9365, 4364, 3605, 1146, 1962],
 [9365, 4364, 3605, 1146, 7696],
 [1667, 1427, 4442, 7416, 9968],
 [9068, 1663, 6806, 1146]]

In [13]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences - changed now
from tensorflow.keras.utils import pad_sequences ## adds zeros in the matrix of each sentence
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1427 5280 7416 4025]
 [   0    0    0    0 1427 5280 7416 5361]
 [   0    0    0    0 1427 1563 7416 1409]
 [   0    0    0 9365 4364 3605 1146 1962]
 [   0    0    0 9365 4364 3605 1146 7696]
 [   0    0    0 1667 1427 4442 7416 9968]
 [   0    0    0    0 9068 1663 6806 1146]]


In [15]:
## Feature Representation
dim = 10

In [21]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [22]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step


2025-06-21 16:33:58.811787: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2025-06-21 16:33:58.813731: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:961] PluggableGraphOptimizer failed: INVALID_ARGUMENT: Failed to deserialize the `graph_buf`.


array([[[-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [ 0.04843784,  0.00601132,  0.02599845, -0.04523146,
         -0.00173323, -0.01091337,  0.03979607,  0.03003948,
         -0.00755871, -0.04532149],
        [ 0.01185949,  0.03311021, -0.02896203,  0.03962597,
          0.04457897, -0.00900279,  0.0430979 , -0.02681354,
         -0.04525464, -0.0293763 ],
        [ 0.01693619, -0.00364392, -0.01027467, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 1427, 5280, 7416, 4025], dtype=int32)

In [28]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


2025-06-21 16:37:05.292201: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:961] PluggableGraphOptimizer failed: INVALID_ARGUMENT: Failed to deserialize the `graph_buf`.


array([[[-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [-0.04357147, -0.03146926, -0.02206907,  0.00444522,
         -0.00142257,  0.03119116,  0.04043574, -0.01542928,
         -0.00497194,  0.01519096],
        [ 0.04843784,  0.00601132,  0.02599845, -0.04523146,
         -0.00173323, -0.01091337,  0.03979607,  0.03003948,
         -0.00755871, -0.04532149],
        [ 0.01185949,  0.03311021, -0.02896203,  0.03962597,
          0.04457897, -0.00900279,  0.0430979 , -0.02681354,
         -0.04525464, -0.0293763 ],
        [ 0.01693619, -0.00364392, -0.01027467, -0.0